version: '3'

services:
  server:
    build:
      context: .
      target: final
    environment:
      - DATABASE_URL=postgres://rs-tree:XXX@rs-tree-db/rs-tree
      - REDIS_URL=redis://rs-tree-session:6379
      - URL=/api
      - COOKIE_KEY=XXX
      - ADMIN=XXX
    networks:
      - dmz
    depends_on:
      rs-tree-db:
        condition: service_healthy
      rs-tree-session:
        condition: service_healthy
  api-doc:
    image: swaggerapi/swagger-ui:latest
    environment:
      - BASE_URL=/apidoc
      - URL=/apidoc/openapi.yaml
    networks:
      - dmz
  rs-tree-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rs-tree
      - POSTGRES_PASSWORD=XXX
      - POSTGRES_DB=rs-tree
    networks:
       - dmz
    volumes:
      - rs-tree-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rs-tree -d rs-tree"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
  rs-tree-session:
    image: redis
    ports:
      - 6379:6379
    networks:
      - dmz
    volumes:
      - rs-tree-session:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
volumes:
  rs-tree-db:
    extern: true
  rs-tree-session:
networks:
  dmz: