version: '3'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://rs-tree:rs-tree@rs-tree-db/rs-tree
      - REDIS_URL=redis://rs-tree-session:6379
    networks:
      - dmz
    depends_on:
      rs-tree-db:
        condition: service_healthy
      rs-tree-session:
        condition: service_healthy
  api-devel:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 80:8080
    networks:
      - dmz
  rs-tree-db:
    image: postgres
    environment:
      - POSTGRES_USER=rs-tree
      - POSTGRES_PASSWORD=rs-tree
      - POSTGRES_DB=rs-tree
    networks:
       - dmz
    volumes:
      - rs-tree-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
  rs-tree-session:
    image: redis
    networks:
      - dmz
    volumes:
      - rs-tree-session:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
volumes:
  rs-tree-db:
  rs-tree-session:
networks:
  dmz: