version: '3'

services:
  server:
    build:
      context: .
      target: final
    environment:
      - DATABASE_URL=postgres://rs-tree:rs-tree@rs-tree-db/rs-tree
      - REDIS_URL=redis://rs-tree-session:6379
      - URL=/api
      - COOKIE_KEY=f000NkKUxyoHeOxr+cPvkdADfyX0MBEqeZ12GsHjTyI3APe1WLuVizJUoDBDRNLYyC5y8SOk9tics/bxTL+etQ==
      - ADMIN=RS-Tr33
    networks:
      - dmz
    depends_on:
      db:
        condition: service_healthy
      session:
        condition: service_healthy
  apidoc:
    image: swaggerapi/swagger-editor:latest
    environment:
     - BASE_URL=/apidoc
     - URL=/apidoc/openapi.yaml
    networks:
      - dmz
  proxy:
    image: caddy:2.7-alpine
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./docs/openapi.yaml:/srv/openapi.yaml
      - proxy_data:/data
      - proxy_config:/config
    networks:
      - dmz
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rs-tree
      - POSTGRES_PASSWORD=rs-tree
      - POSTGRES_DB=rs-tree
    networks:
       - dmz
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rs-tree -d rs-tree"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
  session:
    image: redis
    ports:
      - 6379:6379
    networks:
      - dmz
    volumes:
      - session:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
volumes:
  db:
  session:
  proxy_data:
  proxy_config:
networks:
  dmz: