//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::tree::Entity as Tree;
pub use super::tree_entry::Entity as TreeEntry;
pub use super::url::Entity as Url;
pub use super::user::Entity as User;
